# The following patch adds a directive for certmanager to inject CA into the CRD
#apiVersion: apiextensions.k8s.io/v1
#kind: CustomResourceDefinition
#metadata:
#  annotations:
#    cert-manager.io/inject-ca-from: projectsveltos/projectsveltos-serving-cert # this is hardcoded with conversion-webhook repo
#  name: clusterprofiles.config.projectsveltos.io
